dsn: postgres://test_user:test_password@postgres:5432/test_db?sslmode=disable

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:4433
  flows:
    login:
      ui_url: http://localhost:4433/login
    registration:
      ui_url: http://localhost:4433/registration

courier:
  smtp:
    connection_uri: smtp://stub:stub@mail.local:1025
