version: "3.8"
services:
  db:
    image: postgres:15.2-alpine
    container_name: jovvix-db
    environment:
      POSTGRES_USER: jovvix
      POSTGRES_PASSWORD: jovvix
      POSTGRES_DB: jovvix
      POSTGRES_MULTIPLE_DATABASES: '"kratos-db"'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build:
      context: ./api/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    env_file:
      - ./api/.env.docker
    command: go run app.go migrate up
    volumes:
      - ./api:/jovvix/

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./api/.env.docker
    volumes:
      - redisdata:/root/redis
      - ./api/redis/redis.conf:/usr/local/etc/redis/redis.conf

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
    env_file:
      - ./api/.env.docker
    depends_on:
      - db
      - migration
      - redis
      - kratos
    command: ["./jovvix", "api"]

  web:
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure
    env_file:
      - ./app/.env.docker
    depends_on:
      - api

  kratos_migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=postgres://jovvix:jovvix@db:5432/jovvix?sslmode=disable&search_path=kratos
      - LOG_LEVEL=trace

    command: migrate sql -e --yes
    restart: on-failure
    depends_on:
      - db

  kratos:
    image: oryd/kratos:v1.0.0
    ports:
      - "4433:${SERVE_PUBLIC_PORT:-4433}" # public
      - "4434:${SERVE_ADMIN_PORT:-4434}" # admin

    env_file:
      - ./api/.env.kratos
    command: serve -c /etc/config/kratos/kratos.yml --watch-courier
    restart: always
    depends_on:
      - db
      - kratos_migrate
    volumes:
      - "./api/pkg/kratos:/etc/config/kratos"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9001"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SENDMAIL_SMTP_ADDR: mailpit:1025
      MP_SENDMAIL_FROM: test@test.com

volumes:
  pgdata:
  redisdata:
