version: "3.8"
services:
  postgresdb:
    image: postgres:15.2-alpine
    container_name: golang-api-postgresdb
    environment:
      POSTGRES_USER: golang-api
      POSTGRES_PASSWORD: golang-api
      POSTGRES_DB: golang-api
      POSTGRES_MULTIPLE_DATABASES: '"kratos-db"'
    ports:
    - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    environment:
    - ADMINER_DEFAULT_SERVER=postgresdb
    depends_on:
    - postgresdb

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "3300:3300"
    restart: on-failure
    env_file:
      - ./api/.env.example
    depends_on:
      - postgresdb
      - adminer

  web:
    build:
      context: ./app/
      dockerfile: Dockerfile
      args:
        MODE: example
    ports:
      - "3000:3000"
    restart: on-failure
    env_file:
      - ./app/.env.example
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - MODE=example
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - api

volumes:
  pgdata:
