version: "3.8"
services:
  postgresdb:
    image: postgres:15.2-alpine
    container_name: quiz-app-postgresdb
    environment:
      POSTGRES_USER: quiz-app
      POSTGRES_PASSWORD: quiz-app
      POSTGRES_DB: quiz-app
      POSTGRES_MULTIPLE_DATABASES: '"kratos-db"'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    image: golang:1.22.0-alpine3.19
    restart: on-failure
    platform: linux/amd64
    depends_on:
      - postgresdb
    env_file:
      - ./api/.env.docker
    command: go run app.go migrate up
    volumes:
      - ./api:/go/

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./api/.env.docker
    volumes:
      - redisdata:/root/redis
      - ./api/redis/redis.conf:/usr/local/etc/redis/redis.conf

  api:
    image: golang:1.22.0-alpine3.19
    ports:
      - "3300:3300"
    platform: linux/amd64
    restart: on-failure
    env_file:
      - ./api/.env.docker
    depends_on:
      - postgresdb
      - migration
      - redis
    command: go run app.go api
    volumes:
      - ./api:/go/

  web:
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "5000:4000"
    restart: on-failure
    env_file:
      - ./app/.env.docker
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - api

volumes:
  pgdata:
  redisdata:
