[build]
cmd = "go build -o ./tmp/build/jovvix ."
bin = "./tmp/build/jovvix api"
include_ext = ["go", "tpl", "tmpl", "html", "env", "toml", "json"]

[screen]
clear_on_rebuild = true
keep_scroll = true
