version: "3.8"
services:
  db:
    image: postgres:15.2-alpine
    container_name: quiz-app-postgresdb-saperate
    environment:
      POSTGRES_USER: quiz-app
      POSTGRES_PASSWORD: quiz-app
      POSTGRES_DB: quiz-app
      POSTGRES_MULTIPLE_DATABASES: '"kratos-db", "quiz-app-testing"'
    ports:
      - 5432:5432
    volumes:
      - ./pkg/kratos/kratos-pg-init-script:/docker-entrypoint-initdb.d
      - pgdata1:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/root/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_HOST=localhost
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=0

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9001"

  kratos_migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=postgres://quiz-app:quiz-app@db:5432/quiz-app?sslmode=disable&search_path=kratos
      - LOG_LEVEL=trace
    command: migrate sql -e --yes
    restart: on-failure
    depends_on:
      - db

  kratos:
    image: oryd/kratos:v1.0.0
    ports:
      - "4433:${SERVE_PUBLIC_PORT:-4433}" # public
      - "4434:${SERVE_ADMIN_PORT:-4434}" # admin
    environment:
      - LOG_LEVEL=trace
    env_file:
      - .env.kratos
    command: serve -c /etc/config/kratos/kratos.yml --watch-courier
    restart: always
    depends_on:
      - db
      - kratos_migrate
    volumes:
      - "./pkg/kratos:/etc/config/kratos"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SENDMAIL_SMTP_ADDR: mailpit:1025
      MP_SENDMAIL_FROM: test@test.com

networks:
  host:
    external: true

volumes:
  pgdata1:
