name: Build and Push api

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "api/**"
      - ".github/workflows/test-build-push-api.yaml"      
      - "!**.md"
  pull_request:
    types: ["opened", "reopened", "synchronize", "ready_for_review"]
    branches:
      - develop
      - main
    paths:
      - "api/**"
      - ".github/workflows/test-build-push-api.yaml"
      - "!**.md"

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        timeout-minutes: 2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
        timeout-minutes: 2

      - name: Install Dependencies
        working-directory: ./api
        run: |
          go mod tidy
          go mod vendor
        timeout-minutes: 5

      - name: Run Backend Tests
        working-directory: ./api
        run: go test ./... -v
        timeout-minutes: 5

  build:
    needs: backend-tests
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        timeout-minutes: 5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: improwised/${{ vars.DOCKER-HUB_REPOSITORY_API }}
          tags: |
            type=raw,value=${{ github.head_ref || github.ref_name }}-{{sha}}-{{date 'X'}}
        timeout-minutes: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        timeout-minutes: 2

      - name: Set PR Tags
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "TAGS=test-${{ github.sha }}" >> $GITHUB_ENV
        timeout-minutes: 1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'develop') }}
          tags: ${{ env.TAGS || steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
        timeout-minutes: 10
